name: CI/CD - Deploy

on:
  push:
    branches: [ "Dev" ]
  workflow_dispatch:
jobs:
  deploy-to-minikube:
    runs-on: ubuntu-latest
    name: Deploy to Minikube
    needs: build-and-push
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. List files in the repository (for debugging)
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all files..."
          ls -R .

      - name: 3. Set up and Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: 4. Update Deployment with new Image Tag
        run: |
          sed -i "s|__IMAGE_NAME__|${{ env.DOCKER_IMAGE }}:${{ needs.build-and-push.outputs.image_tag }}|g" app/k8s/deployment.yaml
          echo "--- Updated deployment.yaml (app/k8s/deployment.yaml) ---"
          cat app/k8s/deployment.yaml

      - name: 5. Deploy Application to Minikube
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f app/k8s/deployment.yaml
          kubectl apply -f app/k8s/service.yaml

      - name: 6. Verify Deployment
        run: |
          echo "Waiting for deployment to be ready..."
          kubectl rollout status deployment/car-co2-deployment  --timeout=120s 
          echo -e "\n--- Pod Status ---"
          kubectl get pods
          echo -e "\n--- Service Status ---"
          kubectl get service
    